server:
  port: 8602

spring:
  application:
    name: dubboConsumer

dubbo:
  application:
    name: dubbo-consumer
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://127.0.0.1:2181
