server:
  port: 8601

spring:
  application:
    name: dubboProvider

dubbo:
  application:
    name: dubbo-provider
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.commoninterface.service